# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20170414_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='candidates',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
